#!/bin/bash

killall xcompmgr || return 0
killall conky || return 0
killall tilda || return 0

DOTFILES=~/.dotfiles

xcompmgr &

#xmodmap $DOTFILES/Xmodmap-us-umlauts

conky -c $DOTFILES/conky/bar.conkyrc &
conky -c $DOTFILES/conky/calendar.conkyrc &

cd .config/tilda && git checkout .

tilda &
sleep 3
tilda &
