#!/bin/bash
export QT_QPA_PLATFORMTHEME="qt5ct"

source ~/.autostart
xsettings() {
    sleep 0.2
    # Set default display options
    #~/.bin/dm i
    
    # Reload wallpaper
    # . ~/.fehbg

    # Set keyboard settings
    setxkbmap us_de
    xset r rate 200 60

    # Disable screensaver
    xset s off
    xset -dpms

    # Load more X settings
    xrdb -merge ~/.Xresources

    # Lockscreen
    # systemctl --user start XAutoLock.service

    # StatusLED
    # systemctl --user start StatusLED.service
}

autostart() {
    sleep 0.2

    #mpd ~/.mpd/mpd.conf &
    #pidgin &
    ~/.bin/polybars &
    # dunst &
    # urxvtd &
    redshift-gtk &
    # xcompmgr &
    compton --config ~/.dotfiles/compton/config &
}

wm() {
    ### Binary Space Partitioning Window Manager
    #sxhkd &
    #exec bspwm
    
    ### i3wm
    exec i3

    ### XMonad
    #exec xmobar&
    #exec xmonad
}

xsettings &
autostart &
wm
