#!/bin/bash
export QT_QPA_PLATFORMTHEME="qt5ct"

xsettings() {
    # Set default display options
    ~/.bin/dm
    
    # Reload wallpaper
    . ~/.fehbg

    # Set keyboard settings
    setxkbmap us_de
    xset r rate 200 60

    # Disable screensaver
    xset s off
    xset -dpms

    # Load more X settings
    xrdb ~/.Xresources

    # Start X compositor
    xcompmgr &
}

autostart() {
    mpd ~/.mpd/mpd.conf &
    pidgin &
    dunst &
    urxvtd &
    redshift-gtk &
}

wm() {
    ### Binary Space Partitioning Window Manager
    #sxhkd &
    #exec bspwm
    
    ### i3wm
    exec i3

    ### XMonad
    #exec xmobar&
    #exec xmonad
}

xsettings &
autostart &
wm

