ZSH=/usr/share/oh-my-zsh/

# ~/.oh-my-zsh/themes/
ZSH_THEME="opatut"
export DOTFILES=$HOME/.dotfiles/

DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"

plugins=(git)

source $ZSH/oh-my-zsh.sh

for file in $HOME/.zshrc.d/*.sh; do
    source $file
done
